feat: Removed deprecated events
This addresses the deprecation of the DOMNodeInserted and DOMNodeRemoved. This also add types to variables

Deprecated event types: https://w3c.github.io/uievents/#legacy-event-types

Error: [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.